version: '3.8'

volumes:
  codebase:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/egg/Code/Ghost

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    container_name: devcontainer
    volumes:
      - codebase:/workspaces
    command: sleep infinity

  ghost:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghost
    volumes:
      - codebase:/opt/ghost
    command: sleep infinity
    restart: unless-stopped
    ports:
      - "2368:2368"
    depends_on:
      - db
      - redis
    environment:
      server__host: '0.0.0.0'
      database__host: db
      database__port: 3306
      database__user: root
      database__password: password

  db:
    image: mysql:latest
    container_name: ghost-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ghost

  redis:
    image: redis:7.0.12
    container_name: ghost-redis
